name: Lint
on: [push, pull_request]
jobs:
  build:
    name: Lint add-on configuration
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Run Home Assistant Add-on Linter
        uses: frenck/action-addon-linter@v2.0.0
        with:
          path: "./hassio-google-drive-backup"
